// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_500.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/email.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/notifications/configure.tsx";
import * as $7 from "./routes/notifications/index.tsx";
import * as $8 from "./routes/partials/index.tsx";
import * as $9 from "./routes/partials/pipelines/index.tsx";
import * as $10 from "./routes/pipelines/[id]/delete.tsx";
import * as $11 from "./routes/pipelines/[id]/index.tsx";
import * as $12 from "./routes/pipelines/add.tsx";
import * as $13 from "./routes/pipelines/index.tsx";
import * as $14 from "./routes/pipelines/save.tsx";
import * as $15 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/delete.tsx";
import * as $16 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/attach.tsx";
import * as $17 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/detach.tsx";
import * as $18 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/pause.tsx";
import * as $19 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/schema.tsx";
import * as $20 from "./routes/service/[service]/delete.tsx";
import * as $21 from "./routes/ws/audience-metrics.tsx";
import * as $22 from "./routes/ws/server-error.tsx";
import * as $23 from "./routes/ws/service-map.tsx";
import * as $24 from "./routes/ws/tail.tsx";
import * as $$0 from "./islands/customNodes.tsx";
import * as $$1 from "./islands/drawer/component.tsx";
import * as $$2 from "./islands/drawer/infoDrawer.tsx";
import * as $$3 from "./islands/drawer/operation.tsx";
import * as $$4 from "./islands/drawer/schema.tsx";
import * as $$5 from "./islands/drawer/service.tsx";
import * as $$6 from "./islands/drawer/tail.tsx";
import * as $$7 from "./islands/emailCollectionForm.tsx";
import * as $$8 from "./islands/nav.tsx";
import * as $$9 from "./islands/notifications.tsx";
import * as $$10 from "./islands/pipeline.tsx";
import * as $$11 from "./islands/pipelines.tsx";
import * as $$12 from "./islands/serviceMap.tsx";

const manifest = {
  routes: {
    "./routes/_500.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/email.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/notifications/configure.tsx": $6,
    "./routes/notifications/index.tsx": $7,
    "./routes/partials/index.tsx": $8,
    "./routes/partials/pipelines/index.tsx": $9,
    "./routes/pipelines/[id]/delete.tsx": $10,
    "./routes/pipelines/[id]/index.tsx": $11,
    "./routes/pipelines/add.tsx": $12,
    "./routes/pipelines/index.tsx": $13,
    "./routes/pipelines/save.tsx": $14,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/delete.tsx":
      $15,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/attach.tsx":
      $16,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/detach.tsx":
      $17,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/pause.tsx":
      $18,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/schema.tsx":
      $19,
    "./routes/service/[service]/delete.tsx": $20,
    "./routes/ws/audience-metrics.tsx": $21,
    "./routes/ws/server-error.tsx": $22,
    "./routes/ws/service-map.tsx": $23,
    "./routes/ws/tail.tsx": $24,
  },
  islands: {
    "./islands/customNodes.tsx": $$0,
    "./islands/drawer/component.tsx": $$1,
    "./islands/drawer/infoDrawer.tsx": $$2,
    "./islands/drawer/operation.tsx": $$3,
    "./islands/drawer/schema.tsx": $$4,
    "./islands/drawer/service.tsx": $$5,
    "./islands/drawer/tail.tsx": $$6,
    "./islands/emailCollectionForm.tsx": $$7,
    "./islands/nav.tsx": $$8,
    "./islands/notifications.tsx": $$9,
    "./islands/pipeline.tsx": $$10,
    "./islands/pipelines.tsx": $$11,
    "./islands/serviceMap.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
