// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[info].tsx";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/login.tsx";
import * as $5 from "./routes/pipelines/index.tsx";
import * as $6 from "./routes/rules.tsx";
import * as $$0 from "./islands/flow.tsx";
import * as $$1 from "./islands/pipelines.tsx";

const manifest = {
  routes: {
    "./routes/[info].tsx": $0,
    "./routes/[name].tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/login.tsx": $4,
    "./routes/pipelines/index.tsx": $5,
    "./routes/rules.tsx": $6,
  },
  islands: {
    "./islands/flow.tsx": $$0,
    "./islands/pipelines.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
