// Code generated by counterfeiter. DO NOT EDIT.
package serverfakes

import (
	"context"
	"sync"

	"github.com/streamdal/snitch-go-client/server"
	"github.com/streamdal/snitch-go-client/types"
	"github.com/streamdal/snitch-protos/build/go/protos"
)

type FakeIServerClient struct {
	NewAudienceStub        func(context.Context, *protos.Audience) error
	newAudienceMutex       sync.RWMutex
	newAudienceArgsForCall []struct {
		arg1 context.Context
		arg2 *protos.Audience
	}
	newAudienceReturns struct {
		result1 error
	}
	newAudienceReturnsOnCall map[int]struct {
		result1 error
	}
	NotifyStub        func(context.Context, *protos.Pipeline, *protos.PipelineStep, *protos.Audience) error
	notifyMutex       sync.RWMutex
	notifyArgsForCall []struct {
		arg1 context.Context
		arg2 *protos.Pipeline
		arg3 *protos.PipelineStep
		arg4 *protos.Audience
	}
	notifyReturns struct {
		result1 error
	}
	notifyReturnsOnCall map[int]struct {
		result1 error
	}
	RegisterStub        func(context.Context, *protos.RegisterRequest) (protos.Internal_RegisterClient, error)
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		arg1 context.Context
		arg2 *protos.RegisterRequest
	}
	registerReturns struct {
		result1 protos.Internal_RegisterClient
		result2 error
	}
	registerReturnsOnCall map[int]struct {
		result1 protos.Internal_RegisterClient
		result2 error
	}
	SendMetricsStub        func(context.Context, *types.CounterEntry) error
	sendMetricsMutex       sync.RWMutex
	sendMetricsArgsForCall []struct {
		arg1 context.Context
		arg2 *types.CounterEntry
	}
	sendMetricsReturns struct {
		result1 error
	}
	sendMetricsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIServerClient) NewAudience(arg1 context.Context, arg2 *protos.Audience) error {
	fake.newAudienceMutex.Lock()
	ret, specificReturn := fake.newAudienceReturnsOnCall[len(fake.newAudienceArgsForCall)]
	fake.newAudienceArgsForCall = append(fake.newAudienceArgsForCall, struct {
		arg1 context.Context
		arg2 *protos.Audience
	}{arg1, arg2})
	stub := fake.NewAudienceStub
	fakeReturns := fake.newAudienceReturns
	fake.recordInvocation("NewAudience", []interface{}{arg1, arg2})
	fake.newAudienceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIServerClient) NewAudienceCallCount() int {
	fake.newAudienceMutex.RLock()
	defer fake.newAudienceMutex.RUnlock()
	return len(fake.newAudienceArgsForCall)
}

func (fake *FakeIServerClient) NewAudienceCalls(stub func(context.Context, *protos.Audience) error) {
	fake.newAudienceMutex.Lock()
	defer fake.newAudienceMutex.Unlock()
	fake.NewAudienceStub = stub
}

func (fake *FakeIServerClient) NewAudienceArgsForCall(i int) (context.Context, *protos.Audience) {
	fake.newAudienceMutex.RLock()
	defer fake.newAudienceMutex.RUnlock()
	argsForCall := fake.newAudienceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIServerClient) NewAudienceReturns(result1 error) {
	fake.newAudienceMutex.Lock()
	defer fake.newAudienceMutex.Unlock()
	fake.NewAudienceStub = nil
	fake.newAudienceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIServerClient) NewAudienceReturnsOnCall(i int, result1 error) {
	fake.newAudienceMutex.Lock()
	defer fake.newAudienceMutex.Unlock()
	fake.NewAudienceStub = nil
	if fake.newAudienceReturnsOnCall == nil {
		fake.newAudienceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.newAudienceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIServerClient) Notify(arg1 context.Context, arg2 *protos.Pipeline, arg3 *protos.PipelineStep, arg4 *protos.Audience) error {
	fake.notifyMutex.Lock()
	ret, specificReturn := fake.notifyReturnsOnCall[len(fake.notifyArgsForCall)]
	fake.notifyArgsForCall = append(fake.notifyArgsForCall, struct {
		arg1 context.Context
		arg2 *protos.Pipeline
		arg3 *protos.PipelineStep
		arg4 *protos.Audience
	}{arg1, arg2, arg3, arg4})
	stub := fake.NotifyStub
	fakeReturns := fake.notifyReturns
	fake.recordInvocation("Notify", []interface{}{arg1, arg2, arg3, arg4})
	fake.notifyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIServerClient) NotifyCallCount() int {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	return len(fake.notifyArgsForCall)
}

func (fake *FakeIServerClient) NotifyCalls(stub func(context.Context, *protos.Pipeline, *protos.PipelineStep, *protos.Audience) error) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = stub
}

func (fake *FakeIServerClient) NotifyArgsForCall(i int) (context.Context, *protos.Pipeline, *protos.PipelineStep, *protos.Audience) {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	argsForCall := fake.notifyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeIServerClient) NotifyReturns(result1 error) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = nil
	fake.notifyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIServerClient) NotifyReturnsOnCall(i int, result1 error) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = nil
	if fake.notifyReturnsOnCall == nil {
		fake.notifyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.notifyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIServerClient) Register(arg1 context.Context, arg2 *protos.RegisterRequest) (protos.Internal_RegisterClient, error) {
	fake.registerMutex.Lock()
	ret, specificReturn := fake.registerReturnsOnCall[len(fake.registerArgsForCall)]
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		arg1 context.Context
		arg2 *protos.RegisterRequest
	}{arg1, arg2})
	stub := fake.RegisterStub
	fakeReturns := fake.registerReturns
	fake.recordInvocation("Register", []interface{}{arg1, arg2})
	fake.registerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIServerClient) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *FakeIServerClient) RegisterCalls(stub func(context.Context, *protos.RegisterRequest) (protos.Internal_RegisterClient, error)) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = stub
}

func (fake *FakeIServerClient) RegisterArgsForCall(i int) (context.Context, *protos.RegisterRequest) {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	argsForCall := fake.registerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIServerClient) RegisterReturns(result1 protos.Internal_RegisterClient, result2 error) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	fake.registerReturns = struct {
		result1 protos.Internal_RegisterClient
		result2 error
	}{result1, result2}
}

func (fake *FakeIServerClient) RegisterReturnsOnCall(i int, result1 protos.Internal_RegisterClient, result2 error) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	if fake.registerReturnsOnCall == nil {
		fake.registerReturnsOnCall = make(map[int]struct {
			result1 protos.Internal_RegisterClient
			result2 error
		})
	}
	fake.registerReturnsOnCall[i] = struct {
		result1 protos.Internal_RegisterClient
		result2 error
	}{result1, result2}
}

func (fake *FakeIServerClient) SendMetrics(arg1 context.Context, arg2 *types.CounterEntry) error {
	fake.sendMetricsMutex.Lock()
	ret, specificReturn := fake.sendMetricsReturnsOnCall[len(fake.sendMetricsArgsForCall)]
	fake.sendMetricsArgsForCall = append(fake.sendMetricsArgsForCall, struct {
		arg1 context.Context
		arg2 *types.CounterEntry
	}{arg1, arg2})
	stub := fake.SendMetricsStub
	fakeReturns := fake.sendMetricsReturns
	fake.recordInvocation("SendMetrics", []interface{}{arg1, arg2})
	fake.sendMetricsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIServerClient) SendMetricsCallCount() int {
	fake.sendMetricsMutex.RLock()
	defer fake.sendMetricsMutex.RUnlock()
	return len(fake.sendMetricsArgsForCall)
}

func (fake *FakeIServerClient) SendMetricsCalls(stub func(context.Context, *types.CounterEntry) error) {
	fake.sendMetricsMutex.Lock()
	defer fake.sendMetricsMutex.Unlock()
	fake.SendMetricsStub = stub
}

func (fake *FakeIServerClient) SendMetricsArgsForCall(i int) (context.Context, *types.CounterEntry) {
	fake.sendMetricsMutex.RLock()
	defer fake.sendMetricsMutex.RUnlock()
	argsForCall := fake.sendMetricsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIServerClient) SendMetricsReturns(result1 error) {
	fake.sendMetricsMutex.Lock()
	defer fake.sendMetricsMutex.Unlock()
	fake.SendMetricsStub = nil
	fake.sendMetricsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIServerClient) SendMetricsReturnsOnCall(i int, result1 error) {
	fake.sendMetricsMutex.Lock()
	defer fake.sendMetricsMutex.Unlock()
	fake.SendMetricsStub = nil
	if fake.sendMetricsReturnsOnCall == nil {
		fake.sendMetricsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendMetricsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIServerClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newAudienceMutex.RLock()
	defer fake.newAudienceMutex.RUnlock()
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	fake.sendMetricsMutex.RLock()
	defer fake.sendMetricsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIServerClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.IServerClient = new(FakeIServerClient)
