source "https://rubygems.org"

gem 'rubocop', group: 'development', require: false
gem "streamdal-protos", "0.1.57"
gem "securerandom", "~> 0.3.1"
gem "wasmtime", "~> 18.0.0"
gem "google-protobuf", "~> 3.25"
gem "grpc", "~> 1.62.0"
gem "rake", "~> 13.1"
gem "bozos_buckets", "~> 0.0.2"
gem "httparty"
gem "base64"

gem "rspec", :group => [:test]
gem 'simplecov', require: false, group: :test
gem 'simplecov-cobertura', require: false, group: :test