// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_500.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/configs.tsx";
import * as $5 from "./routes/demo/http/echo.tsx";
import * as $6 from "./routes/demo/http/index.tsx";
import * as $7 from "./routes/email.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/notifications/[id]/delete.tsx";
import * as $10 from "./routes/notifications/[id]/index.tsx";
import * as $11 from "./routes/notifications/add.tsx";
import * as $12 from "./routes/notifications/index.tsx";
import * as $13 from "./routes/notifications/save.tsx";
import * as $14 from "./routes/partials/index.tsx";
import * as $15 from "./routes/partials/notifications/[id]/index.tsx";
import * as $16 from "./routes/partials/notifications/add.tsx";
import * as $17 from "./routes/partials/notifications/index.tsx";
import * as $18 from "./routes/partials/pipelines/[id]/index.tsx";
import * as $19 from "./routes/partials/pipelines/add.tsx";
import * as $20 from "./routes/partials/pipelines/index.tsx";
import * as $21 from "./routes/partials/tail/[id]/index.tsx";
import * as $22 from "./routes/pipelines/[id]/delete.tsx";
import * as $23 from "./routes/pipelines/[id]/index.tsx";
import * as $24 from "./routes/pipelines/add.tsx";
import * as $25 from "./routes/pipelines/index.tsx";
import * as $26 from "./routes/pipelines/save.tsx";
import * as $27 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/delete.tsx";
import * as $28 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/attach.tsx";
import * as $29 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/detach.tsx";
import * as $30 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/pause.tsx";
import * as $31 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/resume.tsx";
import * as $32 from "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/schema.tsx";
import * as $33 from "./routes/service/[service]/delete.tsx";
import * as $34 from "./routes/tail/[id]/index.tsx";
import * as $35 from "./routes/ws/audience-metrics.tsx";
import * as $36 from "./routes/ws/demo/http-request.tsx";
import * as $37 from "./routes/ws/server-error.tsx";
import * as $38 from "./routes/ws/service-map.tsx";
import * as $39 from "./routes/ws/tail.tsx";
import * as $$0 from "./islands/demo/http-request.tsx";
import * as $$1 from "./islands/drawer/component.tsx";
import * as $$2 from "./islands/drawer/infoDrawer.tsx";
import * as $$3 from "./islands/drawer/operation.tsx";
import * as $$4 from "./islands/drawer/schema.tsx";
import * as $$5 from "./islands/drawer/service.tsx";
import * as $$6 from "./islands/drawer/tail.tsx";
import * as $$7 from "./islands/emailCollectionForm.tsx";
import * as $$8 from "./islands/nav.tsx";
import * as $$9 from "./islands/notification.tsx";
import * as $$10 from "./islands/notifications.tsx";
import * as $$11 from "./islands/pipelines/pipeline.tsx";
import * as $$12 from "./islands/pipelines/pipelineActionMenu.tsx";
import * as $$13 from "./islands/pipelines/pipelineHTTP.tsx";
import * as $$14 from "./islands/pipelines/pipelineSchemaValidation.tsx";
import * as $$15 from "./islands/pipelines/pipelineTransform.tsx";
import * as $$16 from "./islands/pipelines/pipelines.tsx";
import * as $$17 from "./islands/pipelines/stepArgs.tsx";
import * as $$18 from "./islands/pipelines/stepCondition.tsx";
import * as $$19 from "./islands/pipelines/stepConditions.tsx";
import * as $$20 from "./islands/pipelines/stepNotification.tsx";
import * as $$21 from "./islands/pipelines/stepNotifications.tsx";
import * as $$22 from "./islands/serviceDisplay.tsx";
import * as $$23 from "./islands/sockets.tsx";

const manifest = {
  routes: {
    "./routes/_500.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/configs.tsx": $4,
    "./routes/demo/http/echo.tsx": $5,
    "./routes/demo/http/index.tsx": $6,
    "./routes/email.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/notifications/[id]/delete.tsx": $9,
    "./routes/notifications/[id]/index.tsx": $10,
    "./routes/notifications/add.tsx": $11,
    "./routes/notifications/index.tsx": $12,
    "./routes/notifications/save.tsx": $13,
    "./routes/partials/index.tsx": $14,
    "./routes/partials/notifications/[id]/index.tsx": $15,
    "./routes/partials/notifications/add.tsx": $16,
    "./routes/partials/notifications/index.tsx": $17,
    "./routes/partials/pipelines/[id]/index.tsx": $18,
    "./routes/partials/pipelines/add.tsx": $19,
    "./routes/partials/pipelines/index.tsx": $20,
    "./routes/partials/tail/[id]/index.tsx": $21,
    "./routes/pipelines/[id]/delete.tsx": $22,
    "./routes/pipelines/[id]/index.tsx": $23,
    "./routes/pipelines/add.tsx": $24,
    "./routes/pipelines/index.tsx": $25,
    "./routes/pipelines/save.tsx": $26,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/delete.tsx":
      $27,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/attach.tsx":
      $28,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/detach.tsx":
      $29,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/pause.tsx":
      $30,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/pipeline/[id]/resume.tsx":
      $31,
    "./routes/service/[service]/component/[component]/[operationType]/op/[operationName]/schema.tsx":
      $32,
    "./routes/service/[service]/delete.tsx": $33,
    "./routes/tail/[id]/index.tsx": $34,
    "./routes/ws/audience-metrics.tsx": $35,
    "./routes/ws/demo/http-request.tsx": $36,
    "./routes/ws/server-error.tsx": $37,
    "./routes/ws/service-map.tsx": $38,
    "./routes/ws/tail.tsx": $39,
  },
  islands: {
    "./islands/demo/http-request.tsx": $$0,
    "./islands/drawer/component.tsx": $$1,
    "./islands/drawer/infoDrawer.tsx": $$2,
    "./islands/drawer/operation.tsx": $$3,
    "./islands/drawer/schema.tsx": $$4,
    "./islands/drawer/service.tsx": $$5,
    "./islands/drawer/tail.tsx": $$6,
    "./islands/emailCollectionForm.tsx": $$7,
    "./islands/nav.tsx": $$8,
    "./islands/notification.tsx": $$9,
    "./islands/notifications.tsx": $$10,
    "./islands/pipelines/pipeline.tsx": $$11,
    "./islands/pipelines/pipelineActionMenu.tsx": $$12,
    "./islands/pipelines/pipelineHTTP.tsx": $$13,
    "./islands/pipelines/pipelineSchemaValidation.tsx": $$14,
    "./islands/pipelines/pipelineTransform.tsx": $$15,
    "./islands/pipelines/pipelines.tsx": $$16,
    "./islands/pipelines/stepArgs.tsx": $$17,
    "./islands/pipelines/stepCondition.tsx": $$18,
    "./islands/pipelines/stepConditions.tsx": $$19,
    "./islands/pipelines/stepNotification.tsx": $$20,
    "./islands/pipelines/stepNotifications.tsx": $$21,
    "./islands/serviceDisplay.tsx": $$22,
    "./islands/sockets.tsx": $$23,
  },
  baseUrl: import.meta.url,
};

export default manifest;
