name: Protos - Pull Request

on:
  pull_request:
    paths:
      - 'libs/protos/**'
      - '.github/workflows/libs-protos-pr.yml'

defaults:
  run:
    working-directory: ./libs/protos

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Protobuf Linting
        uses: plexsystems/protolint-action@v0.4.0
        with:
          configDirectory: ./libs/protos

      - name: Compile protos
        run: |
          make generate/go
          make generate/rust
          make generate/ts
          make generate/protoset
          make generate/python
